### ISSUE TITLE
autocomplete/suggestions?

### ISSUE THREAD

**Issue by jacob87o2** [arthur-melo/just-another-todo-app#104]
Hey, 

Thanks for sharing this really nice and simple TODO app example. 👍 

I have a question about the autocomplete feature I saw here:
https://reactjsexample.com/a-todo-app-built-with-react-redux/

![Autocomplete](https://reactjsexample.com/content/images/2018/11/Todo-App.gif)

Seems it's not included in the current version. 

Just wanted to ask... are you going to publish it also? 🙂

**Comment by arthur-melo** [comment]
Hi @jacob87o2,

Yes, this autocomplete feature isn't available in the application at the moment.
 
I haven't updated it in a while, I'll add this functionality as you requested.

Thanks for checking it out!
